services:
    goapp:
        container_name: goapp
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
        - 8080:8000
        environment:
            DB_Host: db
            DB_PORT: 3306
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${MYSQL_DATABASE}
        depends_on:
            - db

    nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot

    db:
        container_name: mariadb
        image: mariadb:latest
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    db_data:

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes: 
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email mwakeham95@gmail.com -d yuval.store -d www.yuval.store --agree-tos